routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::post('workstations/save', 'WorkstationController@save')->name('workstations.save');
Route::post('workstations/store', 'WorkstationController@store')->name('workstations.store');

Route::resource('workstations', 'WorkstationController');
Route::resource('detailsInventory', 'DetailInventoryController');


Route::get('workstations/{workstation}/assign', 'WorkstationController@assign')->name('workstations.assign');
Route::get('detailsInventory/{detailsInventory}/filtered', 'DetailInventoryController@filtered')->name('detailsInventory.filtered');

app/Models/Workstation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Workstation extends Model
{

    protected $table = 'Equipos';
    protected $fillable = ['udg_id', 'descripcion', 'tipo_equipo', 'marca', 'modelo', 
                          'numero_serie', 'mac', 'ip', 'tipo_conexion', 'detalles', 'verificado', 
                          'img_frente', 'img_serie', 'pdf_factura', 'estado', 'cta', 'IdResguardante', 'activo'];
    public $timestamps = false;

    public function workstationList()
    {
        return $this->belongsTo('App\Models\WorkstationList');
    }

    public function detailInventory()
    {
        return $this->belongsTo('App\Models\DetailInventory');
    }
    public function movement()
    {
        return $this->belongsTo('App\Models\Movement');
    }
    public function employee()
    {
        return $this->belongsTo('App\Models\Employee');
    }
}

app/Http/Controllers/WorkstationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Workstation;
use App\Models\WorkstationList;
use App\Models\Movement;
use App\Models\Area;
use App\Models\Employee;
use Illuminate\Support\Facades\Validator;
use RealRashid\SweetAlert\Facades\Alert;
use DataTables;

class WorkstationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        return view('workstations.index');
    }

    public function datatable()
    {
        $list = WorkstationList::all();
        
        return json_encode(array("data" => $list));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $workstation = Workstation::all();
        return view('workstations.create')->with(compact('workstation'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'udg_id'        =>        ['required', 'string', 'max:20'],
            'descripcion'   =>        ['required', 'string', 'max:50'],
            'hardwareType'  =>        ['required', 'string', 'max:255'],
            'brand'         =>        ['required', 'string', 'max:20'],
            'model'         =>        ['required', 'string', 'max:50'],
            'serialNumber'  =>        ['required', 'string', 'max:30'],
            'mac'           =>        ['required', 'string', 'max:20'],
            'ip'            =>        ['required', 'string', 'max:16'],
            'conectionType' =>        ['required', 'string', 'max:40'],
            'details'       =>        ['required', 'string', 'max:500'],
            'verified'      =>        ['required', 'string', 'max:40'],
            'frontImage'    =>        ['required', 'string', 'max:30'],
            'serialImage'   =>        ['required', 'string', 'max:15'],
            'invoicePDF'    =>        ['required', 'string', 'max:50'],
            'status'        =>        ['required'],
            'cta'           =>        ['required', 'integer', 'max:4'],
            'safeguardID'   =>        ['required', 'integer', 'max:11'],
            'active'        =>        ['required', 'integer', 'max:1']
        ]);

        if ($validator->fails()) {

            Alert::warning('Campos sin llenar', 'Es necesario llenar los campos.');
            return redirect()->route('workstations.create');

        }

        $data = $request->all();
        $workstation = new Workstation();
        $workstation->udg_id = $data['udg_id'];
        $workstation->descripcion = $data['descripcion'];
        $workstation->tipo_equipo = $data['hardwareType'];
        $workstation->marca = $data['brand'];
        $workstation->modelo = $data['model'];
        $workstation->numero_serie = $data['serialNumber'];
        $workstation->mac = $data['mac'];
        $workstation->ip = $data['ip'];
        $workstation->tipo_conexion = $data['conectionType'];
        $workstation->detalles = $data['details'];
        $workstation->verificado = $data['verified'];
        $workstation->img_frente = $data['frontImage'];
        $workstation->img_serie = $data['serialImage'];
        $workstation->pdf_factura = $data['invoicePDF'];
        $workstation->estado = $data['status'];
        $workstation->cta = $data['cta'];
        $workstation->idResguardante = $data['safeguardID'];
        $workstation->activo = $data['active'];
        $workstation->save();
        Alert::success('Registro creado', 'El equipo se dio de alta satisfactoriamente');
        return redirect()->route('workstations.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       
        $workstation = Workstation::find($id);
      
        return view('workstations.edit')->with(compact('workstation'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        $data = $request->all();
        $workstation = Workstation::find($id);
        $workstation->udg_id = $data['udg_id'];
        $workstation->descripcion = $data['descripcion'];
        $workstation->tipo_equipo = $data['hardwareType'];
        $workstation->marca = $data['brand'];
        $workstation->modelo = $data['model'];
        $workstation->numero_serie = $data['serialNumber'];
        $workstation->mac = $data['mac'];
        $workstation->ip = $data['ip'];
        $workstation->tipo_conexion = $data['conectionType'];
        $workstation->detalles = $data['details'];
        $workstation->verificado = $data['verified'];
        $workstation->img_frente = $data['frontImage'];
        $workstation->img_serie = $data['serialImage'];
        $workstation->pdf_factura = $data['invoicePDF'];
        $workstation->estado = $data['status'];
        $workstation->cta = $data['cta'];
        $workstation->idResguardante = $data['safeguardID'];
        $workstation->activo = $data['active'];
        $workstation->update();
        Alert::success('Registro modificado', 'El equipo se actualizo satisfactoriamente');
        return redirect()->route('workstations.index');
    }

    public function assign(){
        return view('workstations.assign');
    }

    public function save(Request $request){
        $data = $request->all();
        $workstation = Workstation::select('id', 'IdResguardante')->where('id', '=',  $data['id_equipo'])->first();
      
        $movement = new Movement();
        $movement->id_equipo = $data['id_equipo'];
        $movement->id_area = (int)$data['id_area'];
        $movement->id_usuario = (int)$data['id_usuario'];
        $movement->id_resguardante = $workstation->IdResguardante;
        $movement->registro = $data['registro'];
        $movement->fecha_hora = date('Y-m-d H-i-s');
        $movement->comentarios = ($data['comentarios'] != "") ? $data['comentarios'] : "-" ;
        $movement->save();
        Alert::success('Registro Asignado', 'El equipo se asigno a un empleado satisfactoriamente');
        return redirect()->route('workstations.index');
    }

    public function assignArea(){

        $queries = Area::select('id', 'sede', 'edificio', 'division', 'unidad')->get();

        $count = 0;

        foreach ($queries as $query)
        {
          
            $results[$count]['id'] = $query->id;
            $results[$count]['value'] =  $query->sede.' - '.$query->edificio.' - '.$query->division.' - '.$query->unidad ;
            $count++;

        }
    
        return response()->json($results);
    }

    public function assignUser(){

        $queries = Employee::select('id', 'nombre')->get();

        $count = 0;

        foreach ($queries as $query)
        {
            $results[$count]['id'] = $query->id;
            $results[$count]['value'] =  $query->nombre ;
            $count++;

        }
        return response()->json($results);
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $workstation = Workstation::find($id);
        $workstation->delete();
        
        
        Alert::success('Registro eliminado', 'El equipo se dio de alta satisfactoriamente');
        return redirect()->route('workstations.index');
    }
}

resources/views/Workstations/assign.blade.php
@extends('layouts.main')
@section('title', 'Equipos')

@section('content')
        <div class="card">
          <div class="card-header bg-light text-bl">
            Asignación del equipo
            <a class="btn btn-danger float-right text-white" href="{{route('workstations.index')}}">Volver</a>
            
          </div> 
          <br>
          <br>
          <br>
          <div class="col-12">
            <form class="form-mequipos row justify-content-center" method="POST" action="{{route('workstations.save')}}">
                @method('POST')
                @csrf
            <input type="hidden" name="id_equipo" value="{{Request::segment(2)}}">
                <div class="col-md-6 col-sm-12">
                    <!-- linea agregada -->
                    <div id="keyAreas" class="form-group dropdow-options">
                        <label class="font-weight-bold">Área</label>
                        <input type="hidden" name="id_area" id="areaId">
                        <input class="form-control" type="text" name="area" id="areaID"  placeholder="Buscar...">
                        
                    </div>
    
    
                    <div id="keyUsuario" class="form-group dropdow-options">
                        <label class="font-weight-bold">Usuario</label>
                        <input type="hidden" name="id_usuario" id="usuarioId">
                        <input class="form-control" type="text" name="usuario" id="usuarioID" placeholder="Buscar...">
                   
                    </div>
    
                    <!-- linea agregada -->
                
    
                    <div class="form-group">
                        <label class="font-weight-bold">Registro</label>
                        <textarea name="registro" class="form-control">Registro Inicial en la Base de Datos</textarea>
                    </div>
    
                    <div class="form-group">
                        <label class="font-weight-bold">Fecha</label>
                        <input type="date" class="form-control" >
                    </div>
    
                    <div class="form-group">
                        <label class="font-weight-bold">Comentarios</label>
                        <textarea name="comentarios" class="form-control"> -</textarea>
                    </div>
    
                    <div class="form-group">
                        <button type="submit" class="btn btn-block btn-success">Guardar</button>
                </div>
            </form>
          </div>
          </div> 

       <script type="text/javascript">
            $(document).ready(function() { 
            $.noConflict();
                $('#areaID').autocomplete({
                    source: "{{route('workstations.assignArea')}}",
                    select: function(event, ui) { 
                        $("#areaId").val(ui.item.id) 
                    }
                });

                $('#usuarioID').autocomplete({
                    source: "{{route('workstations.assignUser')}}",
                    select: function(event, ui) { 
                        $("#usuarioId").val(ui.item.id) 
                    }
                });
            }); 
       </script>
@endsection

resources/views/Workstations/create.blade.php
@extends('layouts.main')
@section('title', 'Registrar Equipo')
@section('content')
<form method="POST" action="{{route('workstations.store')}}">
  @method('POST')
  @csrf
  <div class="card">
    <div class="card-header bg-dark text-white">
        Registro de equipo
    </div>
    <div class="card-body">
        @include('workstations.form')
    </div>
        <div class="card-footer text-muted text-right">
            <a class="btn btn-danger" href="{{route('workstations.index')}}">Volver al listado</a>
            <button type="submit" class="btn btn-success">Guardar</button>
    </div>
  </div>
</form>
@endsection

resources/views/Workstations/edit.blade.php
@extends('layouts.main')
@section('title', 'Modificar Equipos')
@section('content')

<form method="POST" action="{{route('workstations.update', $workstation->id)}}">
  @method('PUT')
  @csrf
  <div class="card">
    <div class="card-header bg-dark text-white">
    Modificar Equipo
    </div>
    <div class="card-body">
        @include('workstations.form')
    </div>
        <div class="card-footer text-muted text-right">
            <a class="btn btn-danger" href="{{route('workstations.index')}}">Cancelar</a>
            <button type="submit" class="btn btn-warning">Actualizar</button>
    </div>
  </div>
</form>
@endsection

resources/views/Workstations/form.blade.php
<div class="row">
    <div class="col-md-4">
     <div class="form-group">
         <label for="udg_id"><strong>ID de UDG</strong></label>
     <input type="text" class="form-control" id="udg_id" maxlength="20" name="udg_id" aria-describedby="udg_idHelp" value="{{( isset($workstation->udg_id) ? $workstation->udg_id : old('udg_id'))}}">
         <small id="udg_idHelp" class="form-text text-muted">ID de UDG</small>
         @if ($errors->has('udg_id'))
            <small class="text-danger">{{$errors->first('udg_id')}}</small>
         @endif
       </div>
    </div>
        <div class="col-md-4">
         <div class="form-group">
             <label for="descripcion"><strong>Descripción del Equipo</strong></label>
         <input type="text" class="form-control" maxlength="50" id="descripcion" name="descripcion" aria-describedby="descripcionHelp" value="{{( isset($workstation->descripcion) ? $workstation->descripcion : old('descripcion'))}}">
             <small id="descripcionHelp" class="form-text text-muted">Descripción del equipo.</small>
             @if ($errors->has('descripcion'))
                <small class="text-danger">{{$errors->first('descripcion')}}</small>
             @endif
           </div>
        </div>
     <div class="col-md-4">
         <div class="form-group">
             <label for="hardwareType"><strong>Tipo de Equipo</strong></label>
             <input type="text" class="form-control" id="hardwareType" name="hardwareType" aria-describedby="hardwareTypeHelp" value="{{( isset($workstation->tipo_equipo) ? $workstation->tipo_equipo : old('tipo_equipo'))}}">
             <small id="hardwareTypeHelp" class="form-text text-muted">Tipo de equipo.</small>
             @if ($errors->has('hardwareType'))
                 <small class="text-danger">{{$errors->first('hardwareType')}}</small>
             @endif
        </div>
     </div>
     <div class="col-md-4">
        <div class="form-group">
            <label for="brand"><strong>Marca del Equipo</strong></label>
            <input type="text" class="form-control" maxlength="20" id="brand" name="brand" aria-describedby="brandHelp" value="{{( isset($workstation->marca) ? $workstation->marca : old('marca'))}}">
            <small id="brandHelp" class="form-text text-muted">Marca del equipo.</small>
            @if ($errors->has('brand'))
                <small class="text-danger">{{$errors->first('brand')}}</small>
            @endif
          </div>
        </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="model"><strong>Modelo del Equipo</strong></label>
            <input type="text" class="form-control" maxlength="50" id="model" name="model" aria-describedby="modelHelp" value="{{( isset($workstation->modelo) ? $workstation->modelo : old('modelo'))}}">
            <small id="modelHelp" class="form-text text-muted">Modelo del equipo.</small>
            @if ($errors->has('model'))
                <small class="text-danger">{{$errors->first('model')}}</small>
            @endif
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="serialNumber"><strong>Número de Serie</strong></label>
            <input type="text" class="form-control" maxlength=""30 id="serialNumber" name="serialNumber" aria-describedby="serialNumberHelp" value="{{( isset($workstation->numero_serie) ? $workstation->numero_serie : old('numero_serie'))}}">
            <small id="serialNumberHelp" class="form-text text-muted">Número de serie.</small>
            @if ($errors->has('serialNumber'))
                <small class="text-danger">{{$errors->first('serialNumber')}}</small>
            @endif
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="mac"><strong>Mac</strong></label>
            <input type="text" class="form-control" maxlength="20" id="mac" name="mac" aria-describedby="macHelp" value="{{( isset($workstation->mac) ? $workstation->mac : old('mac'))}}">
            <small id="macHelp" class="form-text text-muted">Mac.</small>
            @if ($errors->has('mac'))
                <small class="text-danger">{{$errors->first('mac')}}</small>
            @endif
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="ip"><strong>IP</strong></label>
            <input type="text" class="form-control" maxlength="16" id="ip" name="ip" aria-describedby="ipHelp" value="{{( isset($workstation->ip) ? $workstation->ip : old('ip'))}}">
            <small id="ipHelp" class="form-text text-muted">IP del equipo.</small>
            @if ($errors->has('ip'))
                <small class="text-danger">{{$errors->first('ip')}}</small>
            @endif
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="conectionType"><strong>Tipo de Conexión</strong></label>
            <input type="text" class="form-control" maxlength="40" id="conectionType" name="conectionType" aria-describedby="conectionTypeHelp" value="{{( isset($workstation->tipo_conexion) ? $workstation->tipo_conexion : old('tipo_conexion'))}}">
            <small id="conectionTypeHelp" class="form-text text-muted">Tipo de conexión del equipo.</small>
            @if ($errors->has('conectionType'))
                <small class="text-danger">{{$errors->first('conectionType')}}</small>
            @endif
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="details"><strong>Detalles del Equipo</strong></label>
            <input type="text" class="form-control" id="details" name="details" aria-describedby="detailsHelp" value="{{( isset($workstation->detalles) ? $workstation->detalles : old('detalles'))}}">
            <small id="detailsHelp" class="form-text text-muted">Detalles del equipo.</small>
            @if ($errors->has('details'))
                <small class="text-danger">{{$errors->first('details')}}</small>
            @endif
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="verified"><strong>Verificado</strong></label>
            <input type="text" class="form-control" maxlength="40" id="verified" name="verified" aria-describedby="verifiedHelp" value="{{( isset($workstation->verificado) ? $workstation->verificado : old('verificado'))}}">
            <small id="verifiedHelp" class="form-text text-muted">Verificado.</small>
            @if ($errors->has('verified'))
                <small class="text-danger">{{$errors->first('verified')}}</small>
            @endif
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="frontImage"><strong>Imagen de Frente</strong></label>
            <input type="text" class="form-control" maxlength="30" id="frontImage" name="frontImage" aria-describedby="frontImageHelp" value="{{( isset($workstation->img_frente) ? $workstation->img_frente : old('img_frente'))}}">
            <small id="frontImageHelp" class="form-text text-muted">Imagen de frente.</small>
            @if ($errors->has('frontImage'))
                <small class="text-danger">{{$errors->first('frontImage')}}</small>
            @endif
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="serialImage"><strong>Imagen de Serie</strong></label>
            <input type="text" class="form-control" maxlength="15" id="serialImage" name="serialImage" aria-describedby="serialImageHelp" value="{{( isset($workstation->img_serie) ? $workstation->img_serie : old('img_serie'))}}">
            <small id="serialImageHelp" class="form-text text-muted">Imagen de serie.</small>
            @if ($errors->has('serialImage'))
                <small class="text-danger">{{$errors->first('serialImage')}}</small>
            @endif
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="invoicePDF"><strong>PDF de factura</strong></label>
            <input type="text" class="form-control" maxlength="50" id="invoicePDF" name="invoicePDF" aria-describedby="invoicePDFHelp" value="{{( isset($workstation->pdf_factura) ? $workstation->pdf_factura : old('pdf_factura'))}}">
            <small id="invoicePDFHelp" class="form-text text-muted">PDF de factura.</small>
            @if ($errors->has('invoicePDF'))
                <small class="text-danger">{{$errors->first('invoicePDF')}}</small>
            @endif
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="status"><strong>Seleccione estado del Equipo</strong></label>
            <select class="form-control" id="status" name="status" aria-describedby="statusHelp">
                <option value="-1">Seleccione el Estado</option>
                <option value="Activo"  {{ (isset($workstation->id ) && 'Activo' == $workstation->estado)  ? 'selected': old('estado')}}>Activo</option>
                <option value="No Activo"  {{ (isset($workstation->id ) && 'No Activo' == $workstation->estado ) ? 'selected': old('estado')}}>No Activo</option>
                <option value="Baja"  {{ (isset($workstation->id ) && 'Baja' == $workstation->estado ) ? 'selected': old('estado')}}>Baja</option>
            </select>
            <small id="statusHelp" class="form-text text-muted">Seleccione estado del equipo.</small>
            @if ($errors->has('status'))
               <small class="text-danger">{{$errors->first('status')}}</small>
           @endif
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="cta"><strong>CTA</strong></label>
            <input type="number" class="form-control" id="cta" max="4" name="cta" aria-describedby="ctaHelp" value="{{( isset($workstation->cta) ? $workstation->cta : old('cta'))}}">
            <small id="ctaHelp" class="form-text text-muted">CTA.</small>
            @if ($errors->has('cta'))
                <small class="text-danger">{{$errors->first('cta')}}</small>
            @endif
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="safeguardID"><strong>ID Resguardante</strong></label>
            <input type="number" class="form-control" max="11" id="safeguardID" name="safeguardID" aria-describedby="safeguardIDHelp" value="{{( isset($workstation->IdResguardante) ? $workstation->IdResguardante : old('IdResguardante'))}}">
            <small id="safeguardIDHelp" class="form-text text-muted">ID Resguardante.</small>
            @if ($errors->has('safeguardID'))
                <small class="text-danger">{{$errors->first('safeguardID')}}</small>
            @endif
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="active"><strong>Activo</strong></label>
            <input type="number" class="form-control" max="1" id="active" name="active" aria-describedby="activeHelp" value="{{( isset($workstation->activo) ? $workstation->activo : old('activo'))}}">
            <small id="activeHelp" class="form-text text-muted">Activo.</small>
            @if ($errors->has('active'))
                <small class="text-danger">{{$errors->first('active')}}</small>
            @endif
        </div>
    </div>
</div>

resources/views/Workstations/index.blade.php
@extends('layouts.main')
@section('title', 'Equipos')

@section('content')
        <div class="card">
          <div class="card-header bg-light text-bl">
              Lista de Equipos
              <a class="btn float-right text-white" style="background-color: #9a3616" href="{{route('workstations.create')}}"><i class="fas fa-plus-square">&nbsp;</i>Nuevo registro</a>
          </div> 
          <div class="card-body">
             <div class="row">
                <div class="col-12">
                    <table id="workstation_datatable" class="table table-sm table-bordered" style="width:100%">
                      <thead class="tableHeader">
                        <tr>
                          <th class="text-center tablehead">ID</th>
                          <th class="text-center tablehead">Tipo de equipo</th>
                          <th class="text-center tablehead">ID de UDG</th>
                          <th class="text-center tablehead">Marca</th>
                          <th class="text-center tablehead">Modelo</th>
                          <th class="text-center tablehead">Número de<br>Serie</th>
                          <th class="text-center tablehead" style="width: 60%">Descripción</th>
                          <th class="text-center tablehead" style="width: 70%">Ubicación</th>
                          <th class="text-center tablehead" colspan="2" style="width: 10%">Acciones</th>
                        </tr>
                      </thead>
                      <tbody>
                            
                      </tbody>
                    </table>
                </div>
             </div>
          </div>
        </div>
        <script type="text/javascript">

            let edit_route = '{{route('workstations.edit', "_ID_")}}';
            let destroy_route = '{{route('workstations.destroy', "_ID_")}}';
            let assign_route = '{{route('workstations.assign', "_ID_")}}';

              $(document).ready(function() {
                  let language_datatable = {
                  "decimal":        "",
                  "emptyTable":     "No hay registros",
                  "info":           "Mostrando _START_ de _END_ de _TOTAL_ entradas",
                  "infoEmpty":      "Mostrando 0 de 0 de 0 entradas",
                  "infoFiltered":   "(Filtro de _MAX_ entradas totales)",
                  "infoPostFix":    "",
                  "thousands":      ",",
                  "lengthMenu":     "Mostrar _MENU_ entradas",
                  "loadingRecords": "Cargando...",
                  "processing":     "Procesando...",
                  "search":         "Buscar:",
                  "zeroRecords":    "No existen registros con esos valores",
                  "paginate": {
                      "first":      "Primera",
                      "last":       "Ultima",
                      "next":       "Siguiente",
                      "previous":   "Anterior"
                  },
                  "aria": {
                      "sortAscending":  ": activate to sort column ascending",
                      "sortDescending": ": activate to sort column descending"
                  }
              }
                $.noConflict();
                $("#workstation_datatable").DataTable({
                  "ajax": {
                    "url":  "{{route('workstations.datatable')}}",
                    "type": "GET"
                  },
                  language: language_datatable,
                  columns: [
                    {data: "id"},
                    {data: "tipo_equipo"},
                    {data: "udg_id"},
                    {data: "marca"},
                    {data: "modelo"},
                    {data: "numero_serie"},
                    {data: "detalles"},
                    {data: "unidad"}
                    ],
                    "aoColumnDefs": [ 
                      { "aTargets": [8], 
                        "mData": null, "mRender": function (data, type, full) 
                        { 
                            $btn = '<a id="update" tittle="Ver más" href="' + edit_route.replace("_ID_", data.id) + '" class="btn btn-link text-warning"><i class="fas fa-pencil-alt"></i></a>';
                            $btn2 = '<form id="destroy" action="' + destroy_route.replace("_ID_", data.id) + '" method="post">  @method('DELETE') @csrf <button type="submit" class="btn btn-link text-danger"><i class="fas fa-trash"></i></button></form>';
                            $btn3 = '<a id="more" href="' + "" + '" class="btn btn-link text-info"><i class="fas fa-info"></i></a>';
                            $btn4 = '<a id="assignWs" href="' + assign_route.replace("_ID_", data.id) + '" class="btn btn-link text-primary"><i class="fas fa-address-book"></i></a>';
                           
                          return  $btn3.concat($btn, $btn2, $btn4)
                        }
                      } 
                      ] 
                });
            });
        </script>
@endsection